### ISSUE TITLE
@13guff13  tests fail -

### ISSUE THREAD

**Issue by jkanche** [epiviz/epiviz-mbrowser#6]
@13guff13  tests fail - 

```
⋊> ~/P/p/e/github-epiviz-mbrowser on master ◦ npm test                                                                                                (base) 12:38:55

> @ test /Users/kancherj/Projects/public/epiviz-ui/github-epiviz-mbrowser
> mocha --timeout 0  ./test/bootstrap.js --recursive test



  mbrowser test
button "Add Chart" with visibility "visible" clicked
measurements length "11"
selected measurements length "2"
close button "Close"
button "Add Chart" clicked
    ✓ erase selected measurements after reopen dialog (1762ms)
button "Add Chart" with visibility "visible" clicked
    1) measurement according to project/collection/chart
button "Add Chart" with visibility "visible" clicked
    2) initialize m-browser with project and collection, we expect the chart type to be automatically selected based on the measurements
elapsed time:  2545


  1 passing (3s)
  2 failing

  1) mbrowser test
       measurement according to project/collection/chart:
     Error: Evaluation failed: TypeError: Cannot read property 'shadowRoot' of null
    at __puppeteer_evaluation_script__:5:183
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async ExecutionContext.evaluate (node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
      at async JSHandle.evaluate (node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:102:16)
      at async ElementHandle.$$eval (node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:688:24)
      at async DOMWorld.$$eval (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:117:23)
      at async Context.<anonymous> (test/sample.spec.js:87:33)

  2) mbrowser test
       initialize m-browser with project and collection, we expect the chart type to be automatically selected based on the measurements:
     Error: Evaluation failed: TypeError: Cannot read property 'shadowRoot' of null
    at __puppeteer_evaluation_script__:5:183
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async ExecutionContext.evaluate (node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
      at async JSHandle.evaluate (node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:102:16)
      at async ElementHandle.$$eval (node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:688:24)
      at async DOMWorld.$$eval (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:117:23)
      at async Context.<anonymous> (test/sample.spec.js:120:33)



npm ERR! Test failed.  See above for more details.
```

_Originally posted by @jkanche in https://github.com/epiviz/epiviz-mbrowser/issues/5#issuecomment-763005757_

**Comment by 13guff13** [comment]
fixed in https://github.com/epiviz/epiviz-mbrowser/pull/7/commits/b5c91e7b446200af554f2ba5102b9def4b56e30c

**Comment by jkanche** [comment]
@13guff13 yes they still fail

**Comment by jkanche** [comment]
> @13guff13 yes they still fail



> fixed in [b5c91e7](https://github.com/epiviz/epiviz-mbrowser/commit/b5c91e7b446200af554f2ba5102b9def4b56e30c)

yes they still fail. Did you update your fork with the commits from this repo ?

**Comment by jkanche** [comment]
this commit fixes this - https://github.com/epiviz/epiviz-mbrowser/tree/0822f3224098231ae8ba7eb7e496be308b5bcb6c
